kind: pipeline
name: test

trigger:
  event:
  - push

steps:
  - name: lint
    image: pelotech/drone-helm3
    settings:
      mode: lint
      chart: ./keycloak

  - name: test
    image: busybox
    commands:
    - echo "Testing"

---
kind: pipeline
name: promote-dev

trigger:
  branch:
  - main
  event:
  - promote
  target:
  - dev

steps:
  - name: promote-dev
    image: pelotech/drone-helm3
    settings:
      mode: upgrade
      chart: ./keycloak
      release: deploy-dev
      skip_tls_verify: true
    environment:
      KUBE_API_SERVER: https://192.168.56.11:6443
      KUBE_SERVICE_ACCOUNT: helm
      KUBE_TOKEN:
        from_secret: kubernetes_token_dev

---
kind: pipeline
name: promote-prod

trigger:
  branch:
  - main
  event:
  - promote
  target:
  - prod

steps:
  - name: promote-prod
    image: pelotech/drone-helm3
    settings:
      mode: upgrade
      chart: ./keycloak
      release: deploy-prod
      skip_tls_verify: true
    environment:
      KUBE_API_SERVER: https://192.168.56.12:6443
      KUBE_SERVICE_ACCOUNT: helm
      KUBE_TOKEN:
        from_secret: kubernetes_token_prod

