---
apiVersion: skaffold/v2beta29
kind: Config

portForward:
- resourceType: service
  resourceName: ingress-nginx-controller
  namespace: ingress-nginx
  port: 443
  localPort: 443
  address: 0.0.0.0

build:
  artifacts:
  - image: cp5102/keycloak-broker
    context: ./kube-infra/docker/keycloak
    docker:
      buildArgs:
        KEYCLOAK_IDP_HOST: '{{ .KEYCLOAK_IDP_HOST }}'
        MINIKUBE_INGRESS_HOST: '{{ .MINIKUBE_INGRESS_HOST }}'
  #- image: cp5102/gitea
    #context: ./kube-infra/docker/gitea
    #docker:
      #buildArgs:
        #MINIKUBE_INGRESS_HOST: '{{ .MINIKUBE_INGRESS_HOST }}'

deploy:
  kubectl:
    hooks:
      before:
        - host:
            #command: ["./pre-deploy-exec.bash"]
      after:
        - host:
            command: ["./post-deploy-exec.bash"]
    manifests:
      - "kube-infra/k8s/*.yaml"
