---
apiVersion: skaffold/v2beta29
kind: Config

portForward:
- resourceType: service
  resourceName: ingress-nginx-controller
  namespace: ingress-nginx
  port: 443
  localPort: 443
  address: 0.0.0.0

build:
  artifacts:
  - image: cp5102/keycloak-broker
    context: ./infra/docker/keycloak
    docker:
      buildArgs:
        KEYCLOAK_IDP_HOST: '{{ .KEYCLOAK_IDP_HOST }}'

deploy:
  kubectl:
    hooks:
      before:
        - host:
            #command: ["./pre-deploy-exec.bash"]
    manifests:
      - "infra/k8s/*.yaml"
