services:
  proxy:
    build: 
        context: .
        dockerfile: docker/proxy/Dockerfile
    container_name: red_team_proxy
    network_mode: host

  ingress:
    image: nginx:alpine
    container_name: red_team_nginx_ingress 
    volumes:
      - "$PWD/nginx/index.html:/usr/share/nginx/html/index.html"
      - "$PWD/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/nginx/nginx.crt:/etc/nginx/ssl/nginx.crt"
      - "$PWD/nginx/nginx.key:/etc/nginx/ssl/nginx.key"
    networks:
      red_team_network:
        ipv4_address: 172.29.0.2

  phishing_server:
    build: 
        context: .
        dockerfile: docker/phishing_server/Dockerfile
    container_name: red_team_phishing_server
    networks:
      red_team_network:
        ipv4_address: 172.29.0.3

networks:
  red_team_network:
    name: red_team_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
          gateway: 172.29.0.1
