volumes:
  psql_db:
    driver: local

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak

    volumes: 
      - psql_db:/var/lib/postgresql/data
    networks:
      idp_network:
        ipv4_address: 172.28.0.3

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-idp
    command:
      - "start-dev"
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      KC_HTTPS_PORT: 443
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password

      KC_HTTPS_KEY_STORE_FILE: '/opt/keycloak/conf/server.p12'
      #KC_KEY_STORE_PASSWORD: 'password'
    restart: unless-stopped
    volumes:
      - "$PWD/keycloak-idp.p12:/opt/keycloak/conf/server.p12"
    networks:
      idp_network:
        ipv4_address: 172.28.0.2

networks:
  idp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1
