volumes:
  psql_db:
    driver: local

services:
  proxy:
    build: 
        context: .
        dockerfile: docker/proxy/Dockerfile
    container_name: infra_proxy
    network_mode: host

  ingress:
    image: nginx:alpine
    container_name: nginx-ingress 
    volumes:
      - "$PWD/nginx/index.html:/usr/share/nginx/html/index.html"
      - "$PWD/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/nginx/nginx.crt:/etc/nginx/ssl/nginx.crt"
      - "$PWD/nginx/nginx.key:/etc/nginx/ssl/nginx.key"
    ports:
      - "443:443"
    networks:
      idp_network:
        ipv4_address: 172.28.0.2

  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    restart: on-failure # other option: always - if you want persistent through host reboots
    networks:
      idp_network:
        ipv4_address: 172.28.0.53
    volumes:
      - "$PWD/coredns:/etc/coredns"
    command: [ "-conf",  "/etc/coredns/Corefile" ]
   
  postgres:
    image: postgres:14.1-alpine
    container_name: keycloak-idp-db
    restart: always
    volumes: 
      - psql_db:/var/lib/postgresql/data
    networks:
      idp_network:
        ipv4_address: 172.28.0.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    dns:
      - 172.28.0.53

  keycloak:
    depends_on:
      - postgres
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-idp
    restart: unless-stopped
    volumes:
      - "$PWD/keycloak-idp.p12:/opt/keycloak/conf/keystore.p12"
    networks:
      idp_network:
        ipv4_address: 172.28.0.3
    environment:
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HTTP_RELATIVE_PATH: '/auth'
      KC_HTTPS_PORT: 443
      KEYCLOAK_ADMIN: idp_admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HTTPS_KEY_STORE_FILE: '/opt/keycloak/conf/keystore.p12'
      #KC_KEY_STORE_PASSWORD: 'password'
    dns:
      - 172.28.0.53
    ports:
      - "8443:443"   # Allow idp keycloak to be accessible on $(minikube ip):8443
    command:
      - "start-dev"

networks:
  idp_network:
    name: idp_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1
